export const ACCESS_TOKEN_EXPIRES_IN = "15m";
export const REFRESH_TOKEN_EXPIRES_IN_DAYS = 7;
export const MAX_SESSION_AGE_DAYS = 30;

export const REFRESH_TOKEN_EXPIRES_IN_MS =
  REFRESH_TOKEN_EXPIRES_IN_DAYS * 24 * 60 * 60 * 1000;
export const MAX_SESSION_AGE_MS = MAX_SESSION_AGE_DAYS * 24 * 60 * 60 * 1000;

